# Generated by Django 3.0.6 on 2020-05-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200529_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
